# .goreleaser.yml
# Build customization
builds:
  - binary: sql-jobber
    goos:
      - windows
      - darwin
      - linux
      - freebsd
      - openbsd
      - netbsd
    goarch:
      - amd64
    dir: ./cmd/

# Archive customization
archives:
  - format: tar.gz
    files:
      - config.toml.sample
      - README.md
      - LICENSE
